[package]
name = "omni-media-bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = {version = "1.38", features = ["full"]}
serenity = {version = "0.12", features = ["full"]}